# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Carrer')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseTemplate'),
        ),
    ]
