# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
